apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-git-creds
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/component: git-write-back
stringData:
  username: "kp0220"
  password: "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"
type: Opaque